### ISSUE TITLE
Hi I'm getting some errors when running make:

### ISSUE THREAD

**Issue by MrFacundo** [ELmounikor/42-So_long-random-map-generator#1]
maze_generator.cpp: In function ‘int main(int, char**)’:
maze_generator.cpp:156:22: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  156 |    for (int i = 1; i < map.size() - 1; i++){
      |                    ~~^~~~~~~~~~~~~~~~
maze_generator.cpp:157:23: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  157 |     for (int j = 1; j < map[i].size() - 1; j++){
      |                     ~~^~~~~~~~~~~~~~~~~~~
maze_generator.cpp:170:22: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  170 |    for (int i = 0; i < map.size(); i++){
      |                    ~~^~~~~~~~~~~~
maze_generator.cpp:171:23: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  171 |     for (int j = 0; j < map[i].size(); j++){
      |                     ~~^~~~~~~~~~~~~~~
maze_generator.cpp:186:11: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  186 |     if (i != map[i].size() - 1)
      |         ~~^~~~~~~~~~~~~~~~~~~~
maze_generator.cpp:203:22: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::vector<std::__cxx11::basic_string<char> >::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  203 |    for (int i = 0; i < map.size(); i++){
      |                    ~~^~~~~~~~~~~~
maze_generator.cpp:204:23: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  204 |     for (int j = 0; j < map[i].size(); j++){
      |                     ~~^~~~~~~~~~~~~~~
maze_generator.cpp:207:11: error: comparison of integer expressions of different signedness: ‘int’ and ‘std::__cxx11::basic_string<char>::size_type’ {aka ‘long unsigned int’} [-Werror=sign-compare]
  207 |     if (i != map[i].size() - 1)
      |         ~~^~~~~~~~~~~~~~~~~~~~
In file included from /usr/include/c++/9/bits/char_traits.h:39,
                 from /usr/include/c++/9/ios:40,
                 from /usr/include/c++/9/ostream:38,
                 from /usr/include/c++/9/iostream:39,
                 from maze_generator.hpp:4,
                 from maze_generator.cpp:1:
/usr/include/c++/9/bits/stl_algobase.h: In instantiation of ‘static _OI std::__copy_move<false, false, std::random_access_iterator_tag>::__copy_m(_II, _II, _OI) [with _II = const s_cords*; _OI = s_cords*]’:
/usr/include/c++/9/bits/stl_algobase.h:404:30:   required from ‘_OI std::__copy_move_a(_II, _II, _OI) [with bool _IsMove = false; _II = const s_cords*; _OI = s_cords*]’
/usr/include/c++/9/bits/stl_algobase.h:441:30:   required from ‘_OI std::__copy_move_a2(_II, _II, _OI) [with bool _IsMove = false; _II = __gnu_cxx::__normal_iterator<const s_cords*, std::vector<s_cords> >; _OI = __gnu_cxx::__normal_iterator<s_cords*, std::vector<s_cords> >]’
/usr/include/c++/9/bits/stl_algobase.h:474:7:   required from ‘_OI std::copy(_II, _II, _OI) [with _II = __gnu_cxx::__normal_iterator<const s_cords*, std::vector<s_cords> >; _OI = __gnu_cxx::__normal_iterator<s_cords*, std::vector<s_cords> >]’
/usr/include/c++/9/bits/vector.tcc:238:31:   required from ‘std::vector<_Tp, _Alloc>& std::vector<_Tp, _Alloc>::operator=(const std::vector<_Tp, _Alloc>&) [with _Tp = s_cords; _Alloc = std::allocator<s_cords>]’
BFS_search.hpp:56:17:   required from here
/usr/include/c++/9/bits/stl_algobase.h:342:18: error: binding reference of type ‘s_cords&’ to ‘const s_cords’ discards qualifiers
  342 |        *__result = *__first;
      |        ~~~~~~~~~~^~~~~~~~~~
In file included from maze_generator.hpp:12,
                 from maze_generator.cpp:1:
BFS_search.hpp:17:32: note:   initializing argument 1 of ‘s_cords& s_cords::operator=(s_cords&)’
   17 |  s_cords &operator = (s_cords &assign){
      |                       ~~~~~~~~~^~~~~~
cc1plus: all warnings being treated as errors
make: *** [makefile:12: maze_generator.o] Error 1

**Comment by mohamed-souiyeh** [comment]
I think the problem was "because of the strict compilation flags" (of course I had to compare in a more type-safe manner, but I didn't sue me hhhh), so I removed them I hope that fixed it.

sorry for the late response.
